version: '3'
services:
  polkadot:
    build:
      context: .
    ports:
      - "127.0.0.1:30333:30333/tcp"
      - "127.0.0.1:9933:9933/tcp"
    image: neukind/polkadot:latest
    volumes:
      - "polkadot-data:/data"
    command: polkadot

volumes:
  polkadot-data:
